import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/component/Navbar";

import Clients from "@/component/Clients";
import Industries from "@/component/Industries";
import Email from "@/component/Email";
import Hero from "@/component/Hero";
import Banner from "@/component/Banner";
import Testimonial from "@/component/Testimonial";
import Footer from "@/component/Footer";
import Solution from "@/component/Solution";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Banner />
			<Clients />
			<Hero />
			<Solution />
			<Industries />
			<Testimonial />
			<Email />
			<Footer />
		</>
	);
}
