import Head from "next/head";
import { Inter } from "@next/font/google";
import Nav from "@/component/Nav";
import Header from "@/component/Home";
import Main from "@/component/Main";
import Footer from "@/component/Footer";
import { useEffect, useState } from "react";
import { useCartContext } from "@/context/cart_context";

const inter = Inter({ subsets: ["latin"] });
// export async function getStaticProps() {
// 	const res = await fetch(`http://localhost:8000/foods?catagory=${value}`);
// 	const foods = await res.json();

// 	return {
// 		props: {
// 			foods,
// 		},
// 	};
// }

export default function Home() {
	const [foods, setFoods] = useState([]);
	const { selectValue, sort } = useCartContext();
	const [pageCount, setPageCount] = useState(0);
	const [pages, setPages] = useState(0);
	console.log(selectValue);
	useEffect(() => {
		async function fetchData() {
			const res = await fetch(
				`https://fooder-server.onrender.com/foods?catagory=${selectValue}`
			);
			const foods = await res.json();
			const count = foods.length;
			const pages = Math.ceil(count / 5);
			setPageCount(pages);
			{
				sort
					? setFoods(foods.sort((a, b) => a.price - b.price))
					: setFoods(foods.sort((a, b) => b.price - a.price));
			}
		}
		fetchData();
	}, [selectValue, sort]);
	return (
		<>
			<div className="bg-gradient-to-r from-white via-emerald-50 to-blue-100">
				<Head>
					<title>khabaNki | homepage</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<Header />
				<Main
					foods={foods}
					setFoods={setFoods}
					pages={pages}
					setpages={setPages}
					pageCount={pageCount}
				/>
			</div>
		</>
	);
}
